contacts/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns('',
    url(r'^$', views.search, name='search'),
    url(r'^all$', views.all, name='all'),
    url(r'^with_errors$', views.with_errors, name='with_errors'),
    url(r'^with_addresses$', views.with_addresses, name='with_addresses'),
    url(r'^without_addresses$', views.without_addresses, name='without_addresses'),
)

lens/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'', include('contacts.urls')),
)

contacts/models.py
from django.db import models
from django.db.models import Q
from haversine import haversine

from . import utils

ADDRESS_FIELDS = ['Street', 'City', 'State', 'ZIP', 'Country']

class AddressesManager(models.Manager):
    def get_queryset(self):
        return super(AddressesManager, self).get_queryset().select_related('person')

    def with_latlng(self):
        return self.filter(~Q(lat='') & ~Q(lng=''))

    def without_latlng(self):
        return self.filter(Q(lat='') | Q(lng='')).exclude(latlng_error__in=['Multiple results returned', 'No results returned'])

    def near_to(self, latlng, radius_in_miles):
        print '-' * 80
        print 'Finding addresses within {} miles of {}'.format(radius_in_miles, latlng)
        addresses = []
        for address in self.with_latlng():
            print 'Considering: {} ({})'.format(address, address.person)
            distance_in_miles = haversine(address.latlng(), latlng, miles=True)
            print 'Distance in miles:', distance_in_miles
            if distance_in_miles < radius_in_miles:
                print 'Within distance'
                address.distance_in_miles = distance_in_miles
                addresses.append(address)

        print '-' * 80
        return sorted(addresses, key=lambda address: address.distance_in_miles)


class PersonManager(models.Manager):
    def get_queryset(self):
        return super(PersonManager, self).get_queryset().select_related('address_set')


class Person(models.Model):
    address_book_id = models.CharField(max_length=255)
    name = models.CharField(max_length=255, db_index=True)
    organization = models.CharField(max_length=255, null=True)

    objects = PersonManager()

    def __unicode__(self):
        if self.organization:
            return u'{} ({})'.format(self.name, self.organization)
        else:
            return self.name

    def create_address(self, ab_address):
        attrs = dict(zip(ADDRESS_FIELDS, ab_address.elements))
        self.address_set.create(**attrs)


class Address(models.Model):
    person = models.ForeignKey(Person)
    Street = models.CharField(max_length=255)
    City = models.CharField(max_length=255)
    State = models.CharField(max_length=255)
    ZIP = models.CharField(max_length=255)
    Country = models.CharField(max_length=255)
    lat = models.CharField(max_length=255)
    lng = models.CharField(max_length=255)
    latlng_error = models.CharField(max_length=255)

    objects = AddressesManager()

    def __unicode__(self):
        return ', '.join(e for e in self.elements if e)

    @property
    def elements(self):
        return tuple(getattr(self, field) for field in ADDRESS_FIELDS)

    def update_latlng(self):
        try:
            self.lat, self.lng = utils.get_latlng(self.elements)
            self.latlng_error = ''
        except utils.LatLngError as e:
            self.lat, self.lng = '', ''
            print 'Error when updating latlng for {} ({})'.format(self, e)
            self.latlng_error = str(e)
        self.save()

    def latlng(self):
        return float(self.lat), float(self.lng)


class ABPerson(object):
    def __init__(self, raw_person):
        self.raw_person = raw_person

    def name(self):
        first = self.raw_person.valueForProperty_('First')
        last = self.raw_person.valueForProperty_('Last')

        if first is None and last is None:
            return None
        elif first is None:
            return last
        elif last is None:
            return first
        else:
            return u'{} {}'.format(first, last)

    def organization(self):
        return self.raw_person.valueForProperty_('Organization')

    def ab_addresses(self):
        address_prop = self.raw_person.valueForProperty_('Address')
        addresses = set()

        if address_prop is None:
            return set()
        else:
            ixs = range(address_prop.count())
            return {ABAddress(address_prop.valueAtIndex_(ix)) for ix in ixs}


class ABAddress(object):
    def __init__(self, address_dict):
        self.elements = tuple(address_dict.get(field, '') for field in ADDRESS_FIELDS)

contacts/forms.py
from django import forms

class SearchForm(forms.Form):
    distance_in_miles = forms.IntegerField(initial=20)
    postcode = forms.CharField(initial="SG8 7DP")

contacts/views.py
from django.shortcuts import render

from .forms import SearchForm
from .models import Address, Person
from .utils import get_latlng

def all(request):
    context = {
        'people': Person.objects.order_by('name'),
        'form': SearchForm()
    }
    return render(request, 'contacts/all.html', context)

def with_errors(request):
    context = {
        'people': Person.objects.exclude(address__isnull=True).exclude(address__latlng_error='').order_by('name'),
        'form': SearchForm()
    }
    return render(request, 'contacts/all.html', context)

def with_addresses(request):
    context = {
        'people': Person.objects.exclude(address__isnull=True).order_by('name'),
        'form': SearchForm()
    }
    return render(request, 'contacts/all.html', context)

def without_addresses(request):
    context = {
        'people': Person.objects.exclude(address__isnull=False).order_by('name'),
        'form': SearchForm()
    }
    return render(request, 'contacts/all.html', context)

def search(request):
    postcode = request.GET.get('postcode')
    if postcode:
        lat, lng = get_latlng([postcode])

        try:
            distance = int(request.GET['distance_in_miles'])
        except ValueError:
            distance = 20

        form = SearchForm(request.GET)

        if lat is not None and lng is not None:
            nearby_addresses = Address.objects.near_to((lat, lng), distance)
            context = {'form': form, 'addresses': nearby_addresses}
            return render(request, 'contacts/search.html', context)

    form = SearchForm()
    context = {'form': form, 'addresses': None}
    return render(request, 'contacts/search.html', context)

contacts/templates/contacts/all.html
{% extends "contacts/base.html" %}

{% block content %}

<table class="table table-bordered table-striped">
	<thead>
		<tr>
			<th>Name</th>
			<th>Address</th>
			<th>Lat/Lng</th>
		</tr>
	</thead>
	<tbody>
		{% for person in people %}
			{% for address in person.address_set.all %}
				<tr>
					{% if forloop.first %}
						<td>{{ person }}</td>
					{% else %}
						<td></td>
					{% endif %}
					<td>
						{{ address }}
					</td>
					<td>
						{% if address.lat %}
						{{ address.lat }} / {{ address.lng }}
						{% else %}
						{{ address.latlng_error }}
						{% endif %}
					</td>
				</tr>
			{% empty %}
				<tr>
					<td>{{ person }}</td>
					<td></td>
					<td></td>
				</tr>
			{% endfor %}
		{% endfor %}
	</tbody>
</table>

{% endblock %}

contacts/templates/contacts/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en-gb">
<head>
<link rel="stylesheet" href="{% static "css/bootstrap.css" %}" />
<link rel="stylesheet" href="{% static "css/bootstrap-theme.css" %}" />
<style>
	body { padding-top: 70px; }
</style>
<title>Contact Lens</title>
</head>

<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container">
		<form action="{% url 'search' %}" class="navbar-form navbar-left" role="search">
			<div class="form-group">
				<span>Find all contacts within</span>
				<input id="id_distance_in_miles" class="form-control" name="distance_in_miles" type="number" value="{{ form.distance_in_miles.value }}"/>
				<span>miles of</span>
				<input id="id_postcode" class="form-control span4" name="postcode" type="text" value="{{ form.postcode.value }}"/>
			</div>
			<button type="submit" class="btn btn-default">Search</button>
		</form>
		<div class="navbar-header navbar-right">
			<a class="navbar-brand" href="{% url 'search' %}">Contact Lens</a>
		</div>
	</div>
</nav>

<div class="container">
	<p>
	<a href={% url 'all' %}>View all contacts</a>
	|
	<a href={% url 'with_addresses' %}>View contacts with addresses</a>
	|
	<a href={% url 'without_addresses' %}>View contacts without addresses</a>
	|
	<a href={% url 'with_errors' %}>View contacts with errors</a>
	</p>

	{% block content %}{% endblock %}

</div>

</body>
</html>

contacts/templates/contacts/search.html
{% extends "contacts/base.html" %}

{% block content %}

<hr />

{% if addresses %}
	<table class="table bordered table-striped">
		<thead>
			<tr>
				<th>Name</th>
				<th>Address</th>
				<th>Distance in miles</th>
			</tr>
		</thead>
		<tbody>
			{% for address in addresses %}
				<tr>
					<td>{{ address.person }}</td>
					<td>{{ address }}</td>
					<td>{{ address.distance_in_miles|floatformat }}</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>

	<hr />
{% endif %}

<hr />
{% endblock %}